<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>IO Blocks LED</title>
	<!--<link rel="stylesheet" href="jquery-ui-1.10.3/themes/base/jquery.ui.all.css">-->
	<script src="jquery-ui-1.10.3/jquery-1.9.1.js"></script>
	<script src="jquery-ui-1.10.3/ui/jquery.ui.core.js"></script>
	<script src="jquery-ui-1.10.3/ui/jquery.ui.widget.js"></script>
	<script src="jquery-ui-1.10.3/ui/jquery.ui.button.js"></script>
	<script src="jquery-ui-1.10.3/jquery.rotel.js"></script>
  <!--<link rel="stylesheet" href="/resources/demos/style.css" />-->
  
  
<style>
	.head {
		height:50px;
	}
	.head2 {
		height:140px;
	}
	.toggler { 
		width: 615px; 
		height: 430px; 
		position: relative; 
	}
	.button_led {
		width:34px;
		height:70px;
		-moz-box-shadow:inset 0px 1px 0px 0px #c1ed9c;
		-webkit-box-shadow:inset 0px 1px 0px 0px #c1ed9c;
		box-shadow:inset 0px 1px 0px 0px #c1ed9c;
		background-color:#9dce2c;
		-moz-border-radius:6px;
		-webkit-border-radius:6px;
		border-radius:6px;
		display:inline-block;
		color:#ffffff;
		font-family:arial;
		font-size:15px;
		font-weight:bold;
		padding:6px 24px;
		text-decoration:none;
		text-shadow:1px 1px 0px #689324;
	}/*.button_led:hover {
		background-color:#8cb82b;
	}*/
	.button_led_active {
		-moz-box-shadow:inset 0px 1px 0px 0px #f29c93;
		-webkit-box-shadow:inset 0px 1px 0px 0px #f29c93;
		box-shadow:inset 0px 1px 0px 0px #f29c93;
		background-color:#fe1a00;
		-moz-border-radius:6px;
		-webkit-border-radius:6px;
		border-radius:6px;
		display:inline-block;
		color:#ffffff;
		font-family:arial;
		font-size:15px;
		font-weight:bold;
		padding:6px 24px;
		text-decoration:none;
		text-shadow:1px 1px 0px #b23e35;
	}
</style>
<style type="text/css">
.button_top {
	-moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	-webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5) );
	background:-moz-linear-gradient( center top, #79bbff 5%, #378de5 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
	background-color:#79bbff;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #84bbf3;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:8px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #528ecc;
}.button_top:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #378de5), color-stop(1, #79bbff) );
	background:-moz-linear-gradient( center top, #378de5 5%, #79bbff 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#378de5', endColorstr='#79bbff');
	background-color:#378de5;
}.button_top:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
.button_top1 {	-moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	-webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5) );
	background:-moz-linear-gradient( center top, #79bbff 5%, #378de5 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
	background-color:#79bbff;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #84bbf3;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:8px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #528ecc;
}
.button_top11 {-moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	-webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5) );
	background:-moz-linear-gradient( center top, #79bbff 5%, #378de5 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
	background-color:#79bbff;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #84bbf3;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:8px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #528ecc;
}
</style>
  
  <script>
  var degree = 0;
  	$(function() {
//		$(".button_led").mouseover()
    	$( ".button_led" ).click(function() {
			var status = 0;
			if($(this).attr('class')=="button_led"){
				status = 1;
			}
			var data = "q"+this.id+status;
			$(this).toggleClass( "button_led_active" ).fadeIn();
			$.post("test.php",
			{
				message:data
			},
			function(data,status){
			//alert("Data: " + data + "\nStatus: " + status);
			});
			return false;
		});
		$("#rotate").click(function() {
			degree+=90;
			if (degree%180==0){
				$( "#top" ).removeClass( "head2");
				$( "#top" ).addClass( "head");
			} else {
				$( "#top" ).removeClass( "head");
				$( "#top" ).addClass( "head2");
			}
			$('.toggler').rotTo(degree);  
		});
		$(".mode").click(function() {
			var data=this.id;
			$.post("test.php",
			{
				message:data
			},
			function(data,status){
			//alert("Data: " + data + "\nStatus: " + status);
			});
		});
  });
  </script>
</head>

<body>
<div id="top" class="head">
	<button id="rotate" class="button_top">Rotate</button>
  <button id="m0" class="mode button_top">Mode 0</button>
	<button id="m1" class="mode button_top">Mode 1</button>
</div>
<div class="toggler">
<? 
	for($i=1;$i<=5;$i++){
		for($j=1;$j<=7;$j++) {
?>
  <div id="<? echo $j.$i?>" class="button_led"></div>
 <? } } ?>
</div>
</body>
</html>